package io.github.rysefoxx.enums;

public enum AnimatorDirection {

    DIAGONAL_TOP_LEFT,
    DIAGONAL_TOP_RIGHT,
    DIAGONAL_BOTTOM_LEFT,
    DIAGONAL_BOTTOM_RIGHT,
    VERTICAL_UP_DOWN,
    VERTICAL_DOWN_UP,
    HORIZONTAL_LEFT_RIGHT,
    HORIZONTAL_RIGHT_LEFT,
}
